import Head from 'next/head'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     {/* Header */}
     <Header />

     {/* Nav */}
     <Nav />

     {/* Results */}
     <Results />
        
    </div>
  )
}
